### ISSUE TITLE
`fxhash dev` error when downloading update for fxlens

### ISSUE THREAD

**Issue by m4xshen** [fxhash/fxhash-package#48]
I run `fxhash dev` and then it outputs:

```
✅  @fxhash/project-sdk already update to date.
need update for fxlens
❌ error on: downloading update for fxlens
Error: EXDEV: cross-device link not permitted, rename '/tmp/fxhash-cli/build' -> '/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/static/fxlens'
    at Object.renameSync (node:fs:1033:11)
    at Object.update (/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-73KLPOU4.js:183:18)
    at async /usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-73KLPOU4.js:44:23
    at async Object.step (/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-2YPNYSAB.js:101:19)
    at async /usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-73KLPOU4.js:42:32
    at async Promise.all (index 0)
    at async updateToolkit (/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-73KLPOU4.js:27:10)
    at async Object.handler (/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/dist/chunk-NBWEXRVY.js:98:7) {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/tmp/fxhash-cli/build',
  dest: '/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/static/fxlens'
}
❗ EXDEV: cross-device link not permitted, rename '/tmp/fxhash-cli/build' -> '/usr/lib/node_modules/fxhash/node_modules/@fxhash/cli/static/fxlens'
Starting anyways...


[fxlens] fx(lens) is running on http://localhost:3300

[project] your project is running on http://localhost:3301

opening fxlens with project as target: http://localhost:3300/?target=http://localhost:3301

[project] compiled successfully @ 06:56:14
```

**Comment by iuriguilherme** [comment]
@m4xshen that javascript library can't make links on different filesystems. Looks like you are using a different filesystem in your project directory, like running that command on WSL Linux in a Windows folder.
